// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACardMeta: typeof import('@arco-design/web-vue')['CardMeta']
    ACarousel: typeof import('@arco-design/web-vue')['Carousel']
    ACarouselItem: typeof import('@arco-design/web-vue')['CarouselItem']
    APagination: typeof import('@arco-design/web-vue')['Pagination']
    News: typeof import('./src/components/News.vue')['default']
    NewsCard: typeof import('./src/components/NewsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
